apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucia-spark-endpoint
spec:
  replicas: {{ .Values.services.replicas }}
  selector:
    matchLabels:
      app: lucia-spark-endpoint
  template:
    metadata:
      labels:
        app: lucia-spark-endpoint
    spec:
      containers:
        - name: lucia-spark-endpoint
          command: ["/bin/sh"]
          args: ["-c", "python -m flask --app spark_endpoint/app.py run --host=0.0.0.0"]
          image: montaraio/lucia-data
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              {{- if .Values.db.createPostgres }}
              value: "{{ .Release.Name}}-postgresql"
              {{- else }}
              value:  {{ .Values.db.host }}
              {{- end }}
            - name: DB_PORT
              value: {{ .Values.postgresql.containerPorts.postgresql | quote }}
            - name: DB_PW
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: KAFKA_HOST
              value: "{{ .Release.Name }}-kafka"
            - name: KAFKA_PORT
              value: "9092"
            - name: NODE_ENV
              value: local
