version: '3.8'

services:
  db:
    image: kartoza/postgis:13-3.1
    container_name: db
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=postgres,data_pipeline
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      # - POSTGRES_MULTIPLE_EXTENSIONS=postgis,metrics,org
      # - POSTGRES_DBNAME=postgis,metrics,org
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
    networks:
      - lucia-network
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/data_pipeline -schemas=postgres -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ../env-setup/migrations:/flyway/sql
    networks:
      - lucia-network
    depends_on:
      db:
        condition: service_healthy
  lucia-web-backend:
    image: avivvegh90/lucia-backend
    container_name: lucia-web-backend
    ports:
      - 3001:3000
    networks:
      - lucia-network
    environment:
      NODE_ENV: local
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PW: postgres
    depends_on:
      db:
        condition: service_healthy
  lucia-web-ui:
    image: avivvegh90/lucia-frontend
    container_name: lucia-web-ui
    ports:
      - 8080:80
    networks:
      - lucia-network
    environment:
      NODE_ENV: local
      BACKEND_URL: "http://localhost:3001"
    depends_on:
      - lucia-web-backend
networks:
  lucia-network:


