version: '3.8'

services:
  db:
    image: kartoza/postgis:13-3.1
    environment:
      - POSTGRES_DB=data_pipeline
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
    networks:
      - lucia-network
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/data_pipeline -schemas=postgres -user=postgres -password=postgres migrate
    ports:
      - 5111:5111
    volumes:
      - ../env-setup/migrations:/flyway/sql
    networks:
      - lucia-network
    depends_on:
      - db
  lucia-web-backend:
    image: avivvegh90/lucia-backend
    ports:
      - 3001:3000
    networks:
      - lucia-network
    environment:
      NODE_ENV: local
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PW: postgres
    depends_on:
      - db
      - flyway
  lucia-web-ui:
    image: avivvegh90/lucia-frontend
    ports:
      - 8080:80
    networks:
      - lucia-network
    environment:
      NODE_ENV: local
      BACKEND_URL: "http://localhost:3001"
    depends_on:
      - lucia-web-backend
networks:
  lucia-network:


