#edit this hostname to the domain name where the service will run,
#in case of AWS it could be the LB DNS name (for example *.us-east-1.elb.amazonaws.com)
hostname: localhost
services:
  replicas: 1
db:
  createPostgres: true
  host: ~
postgresql:
  auth:
    username: lucia
    database: data_pipeline
    password: lucia
  architecture: standalone
  containerPorts:
    postgresql: 5432
  primary:
#    service:
#      type: LoadBalancer
    persistence:
      enabled: false
#      existingClaim: postgres-pv-claim
  volumePermissions:
    enabled: false
  replication:
    enabled: false
kafka:
  autoCreateTopicsEnable: true
  persistence:
    enabled: false
#    existingClaim: kafka-pv-claim
  zookeeper:
    persistence:
      enabled: false
  volumePermissions:
    enabled: false
