apiVersion: v1
kind: Service
metadata:
  name: lucia-spark-job-processor
spec:
  type: ClusterIP
  selector:
    app: lucia-spark-job-processor
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000